import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Lenis from "./components/Lenis";
import ScrollToTop from "./components/ScrollToTop";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${poppins} antialiased`}
      >
        <Navbar/>
        <Lenis>
          <ScrollToTop/>
          {children}
        </Lenis>
        <Footer/>
      </body>
    </html>
  );
}
